### ISSUE TITLE
Python 3 version of circle crater ? 

### ISSUE THREAD

**Issue by mmetois** [sbraden/circle-craters#18]
Thank you for developing this usefull open tool for Qgis. In its current form, the plugin is deprecated for python 3 QGIS based releases. Are you planning moving the plugin to python 3 so it could be used with the most up to date versions ? 

Best, 
Marianne

**Comment by afrigeri** [comment]
Hi Marianne,  
CC is getting back in business in QGIS3.16. see #19 
Alessandro

**Comment by sbraden** [comment]
Closing this issue since @afrigeri updated circle-craters for QGIS 3.
